version: '3.4'
services:
  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-tenant

  cdp-uploader:
    image: defradigital/cdp-uploader:${CDP_UPLOADER_VERSION:-latest}
    ports:
      - '7337:7337'
    links:
      - 'redis:redis'
    depends_on:
      redis:
        condition: service_started
    env_file:
      - 'compose/aws.env'
      - 'compose/secrets.env'
    environment:
      PORT: 7337
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: "true"
      MOCK_VIRUS_SCAN_ENABLED: "true"
      MOCK_VIRUS_RESULT_DELAY: 3
      SQS_ENDPOINT: http://localstack:4566
      S3_ENDPOINT: http://localstack:4566
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      S3_QUARANTINE_BUCKET: cdp-uploader-quarantine
      S3_CLEAN_BUCKET: ai-defra-search-uploads
    networks:
      - cdp-tenant

  ai-defra-search-frontend:
    build:
      target: development
    ports:
      - '3000:3000'
    links:
      - 'redis:redis'
    depends_on:
      redis:
        condition: service_started
      cdp-uploader:
        condition: service_started
    env_file:
      - 'compose/aws.env'
      - 'compose/secrets.env'
    volumes:
      - ./src/:/home/node/src
      - ./package.json:/home/node/package.json
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
    networks:
      - cdp-tenant

networks:
  cdp-tenant:
    external: true
    name: ai-defra-search-data_cdp-tenant
