version: '3.4'
services:
  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-tenant

  ai-defra-search-frontend:
    build:
      target: development
    ports:
      - '3000:3000'
    links:
      - 'redis:redis'
    depends_on:
      redis:
        condition: service_started
    env_file:
      - 'compose/aws.env'
      - 'compose/secrets.env'
    volumes:
      - ./src/:/home/node/src
      - ./package.json:/home/node/package.json
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
    networks:
      - cdp-tenant

networks:
  cdp-tenant:
    driver: bridge
